# Defines infrastructure containers:
    #   PostgreSQL
    #   Redis
    # This allows consistent environments everywhere.

# What This Step Does: Creates FULL infrastructure orchestration.
# Now Docker Compose will manage:
  # APIs
  # workers
  # Redis
  # PostgreSQL
# automatically.


# version: "3.9"

services:

  postgres:

    image: postgres:15

    container_name: pulsepay_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pulsepay

    #docker healthcheck: Currently Docker only knows:Container Running
    #It does NOT know: Application Healthy, A crashed app can still leave a container alive.
    healthcheck:            
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:

    image: redis:7

    container_name: pulsepay_redis

    ports:
      - "6379:6379"
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  fastapi:

    build: .

    container_name: pulsepay_fastapi

    command: >
      uvicorn backend.app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis
    
    healthcheck:
      test: ["CMD-SHELL","python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health')\""]
      interval: 30s
      timeout: 10s
      retries: 3

    env_file:
      - .env

    volumes:
      - .:/app


  payment_worker:

    build: .

    container_name: pulsepay_payment_worker

    command: >
      celery -A backend.core.celery_app
      worker
      -Q payment_queue
      --loglevel=info

    depends_on:
      - redis
      - postgres

    env_file:
      - .env

    volumes:
      - .:/app


  webhook_worker:

    build: .

    container_name: pulsepay_webhook_worker

    command: >
      celery -A backend.core.celery_app
      worker
      -Q webhook_queue
      --loglevel=info

    depends_on:
      - redis
      - postgres

    env_file:
      - .env

    volumes:
      - .:/app


volumes:
  postgres_data: