"""create system metrics table

Revision ID: f8b1bf9510f5
Revises: fc62e2746286
Create Date: 2026-05-28 16:40:35.354243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b1bf9510f5'
down_revision: Union[str, Sequence[str], None] = 'fc62e2746286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_metrics',
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('metric_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_metrics')
    # ### end Alembic commands ###
